### ISSUE TITLE
steal some code for broom.mixed?

### ISSUE THREAD

**Issue by bbolker** [JWiley/postMCMCglmm#1]
Hi Josh,

As you can see from 

  https://stackoverflow.com/questions/47598123/how-do-i-extract-random-effects-from-mcmcglmm/47598440#47598440

some folks have found your code useful.
Would you be OK if I took some of it (with attribution) to include in https://github.com/bbolker/broom.mixed ?

**Comment by JWiley** [comment]
Hi Ben,

Of course!  Please use anything useful --- I'm not fussed about attribution.  I would be interested to know what you end up making.  I work in STAN now more than MCMCglmm but I still use it from time to time and I've always thought it a shame I didn't more actively keep up some extractors and post hoc plots, summary stats, etc. for it.

Best,

Josh
